# General Settings
title: Hongbo's homepage
description: Hongbo's web portfolio to exhibit my skills to potential employer.
url: https://username.github.io
baseurl: / # Used to set the base URL for your site, which is used for generating links to your content.

# Jekyll settings
theme: jekyll-theme-minimal # The name of the Jekyll theme you want to use.
layout: default # The name of the layout file you want to use.
highlighter: coderay # The name of the code highlighter you want to use.

# Custom settings
disqus: # Your Disqus shortname, if you want to enable Disqus comments.
google_analytics: # Your Google Analytics tracking ID, if you want to enable Google Analytics.

# Plugins
plugins:
  - jekyll-assets
  - jekyll-seo-tag

# Collections
collections:
  posts: # The name of your posts collection.
  pages: # The name of your pages collection.

