name: Status
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Building..."
          npm run build
      - uses: actions/set-status@v1
        with:
          state: "success"
          target: "https://github.com/hongbo-wei/hongbo-wei.github.io/actions/workflows/static.yml"
          description: "The status badge workflow has run successfully."
