name: Status
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Building..."
          npm run build
      - uses: actions/set-status@v1
        with:
          state: ${{ success ? 'success' : 'failing' }}
          target: "https://github.com/${GITHUB_REPOSITORY}/actions/workflows/status.yml"
          description: "The status badge workflow has run successfully."
